Controllers/HomeController.cs
using GraphTutorial.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Identity.Web;
using System.Diagnostics;
using System.Threading.Tasks;

namespace GraphTutorial.Controllers
{
    public class HomeController : Controller
    {
        // ITokenAcquisition _tokenAcquisition;
        private readonly ILogger<HomeController> _logger;

        // Get the ITokenAcquisition interface via
        // dependency injection(disabled)
        public HomeController(
            // ITokenAcquisition tokenAcquisition,
            ILogger<HomeController> logger)
        {
            // _tokenAcquisition = tokenAcquisition;
            _logger = logger;
        }

        // public async Task<IActionResult> Index()
        // {
        //     // TEMPORARY
        //     // Get the token and display it
        //     try
        //     {
        //         string token = await _tokenAcquisition
        //             .GetAccessTokenForUserAsync(GraphConstants.Scopes);
        //         return View().WithInfo("Token acquired", token);
        //     }
        //     catch (MicrosoftIdentityWebChallengeUserException)
        //     {
        //         return Challenge();
        //     }
        // }
            public IActionResult Index()
            {
                return View();
            }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        [AllowAnonymous]
        public IActionResult ErrorWithMessage(string message, string debug)
        {
            return View("Index").WithError(message, debug);
        }
    }
}

Controllers/UserController.cs
using GraphTutorial.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Identity.Web;
using Microsoft.Graph;
using Microsoft.Graph.Auth;
using Microsoft.Identity.Client;

using System.IO;
using System.Collections.Generic;
using System.Threading.Tasks;


namespace GraphTutorial.Controllers{

 public class UserController:Controller{


public IActionResult Home(){


    return View();
}


public readonly static string[] UserScope =
        {
            "User.ReadWrite"};






GraphServiceClient _graphClient{get;set;}

    public UserController ( GraphServiceClient graphClient)
            
        {
            _graphClient = graphClient;
            
        }

                List<User>MyUsers = null;
                IGraphServiceUsersCollectionPage users = null;


    [HttpGet ]  
  [AuthorizeForScopes(Scopes = new[] { "User.Read" })]
            public async  Task <IActionResult> Index(){



                     users =  await _graphClient.Users.Request()
                                                                        .Select("displayName,mail,userPrincipalName,city")
                                                                        .GetAsync();

                                         MyUsers = new List<User>();

                                        
                                            
                        
                                        foreach (var u in users)
                                        {

                                            MyUsers.Add(new User
                                            {

                                                Id = u.Id,
                                                DisplayName = u.DisplayName,
                                                Mail = u.Mail,
                                                UserPrincipalName = u.UserPrincipalName,
                                                JobTitle =  u.JobTitle,
                                                City = u.City
                               

                                            });

                                            
                                        }
                return View(users);
            }



public IActionResult UserCreateForm(){

    return View();
}


[HttpPost]
  [AuthorizeForScopes(Scopes = new[] { "User.ReadWrite" })]
public async Task<IActionResult> CreateUser([Bind("DisplayName,UserPrincipalName")]User user){

    

// var user = new User
// {
// 	AccountEnabled = true,
// 	DisplayName = "Ariel Schnell",
// 	MailNickname = "AdeleS",
// 	UserPrincipalName = "Ariel@dkwebbdesign.onmicrosoft.com",
// 	PasswordProfile = new PasswordProfile
// 	{
// 		ForceChangePasswordNextSignIn = true,
// 		Password = "xWwvJ]6NMw+bWH-d"
// 	}
// };
        user.AccountEnabled = true;
        // var fullName = user.GivenName +" "+ user.Surname;
        // user.DisplayName = user.GivenName;
        // user.City="RequiredForCompatibility";
        user.MailNickname = "RequiredForCompatibility";
        user.PasswordProfile = new PasswordProfile
	{
		ForceChangePasswordNextSignIn = true,
		Password = "xWwvJ]6NMw+bWH-d"
	};


            if (ModelState.IsValid)
            {

                await _graphClient.Users
                    .Request()                 
                    .AddAsync(user);
            }
   
   
    return View(user);

}


    [HttpPatch]     
    [ValidateAntiForgeryToken]
  [AuthorizeForScopes(Scopes = new[] {  "User.ReadWrite.All", })]
            public async Task<IActionResult> UpdateUser( [Bind("JobTitle,DisplayName,UserPrincipalName")] User user){


                                
                // user.JobTitle ="Test..";

                await _graphClient.Users[user.Id]
                    .Request()
                    // .Select("jobTitle,mail,userPrincipalName")
                    .UpdateAsync(user);
                
                
                return View(user);
            }


       

public IActionResult UserDeleteForm(){

    return View();
}


   
    [HttpDelete ]     
    [ValidateAntiForgeryToken]
  [AuthorizeForScopes(Scopes = new[] { "User.ReadWrite" })]
            public async Task<IActionResult> DeleteUser( [FromBody] User user){


                                
 
               await _graphClient.Users[user.UserPrincipalName]
	                    .Request()
	                    .DeleteAsync();

                
                return View(user);
            }



 }
   
 
 }
 

Views/User/IndexViewComponent.cs
using Microsoft.Graph;

using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.Identity.Web;
using Microsoft.AspNetCore.Mvc;
using System.Text.RegularExpressions;

namespace GraphTutorial.Views.User{





    public class IndexViewComponent : ViewComponent{



                    GraphServiceClient _graphClient{get;set;}

                public IndexViewComponent ( GraphServiceClient graphClient)
                        
                    {
                        _graphClient = graphClient;
                        
                    }

        
                

             
                            public async Task<IViewComponentResult> InvokeAsync(){  
    
                                 IGraphServiceUsersCollectionPage users = null;
                List<Microsoft.Graph.User>MyUsers = null;

                     users =  await _graphClient.Users.Request()
                                                                        .Select("displayName,mail,userPrincipalName")
                                                                        .GetAsync();

                                         MyUsers = new List<Microsoft.Graph.User>();

                                        
                                            
                        
                                        foreach (var u in users)
                                        {

                                            MyUsers.Add(new Microsoft.Graph.User
                                            {

                                                Id = u.Id,
                                                DisplayName = u.DisplayName,
                                                Mail = u.Mail,
                                                UserPrincipalName = u.UserPrincipalName
                                            });

                                            
                                        }
                             return View(users);

   
                               
                
                                                       }


         }
    
    
    
    
    
    
    }

Views/User/UserCreateViewComponent.cs
using Microsoft.Graph;

using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;

using Microsoft.AspNetCore.Mvc;
using System.Text.RegularExpressions;

namespace GraphTutorial.Views.User{





    public class UserCreateViewComponent : ViewComponent{



                    GraphServiceClient _graphClient{get;set;}

                public UserCreateViewComponent ( GraphServiceClient graphClient)
                        
                    {
                        _graphClient = graphClient;
                        
                    }


                            public async Task<IViewComponentResult> InvokeAsync(){  
    


   
                                    return View();
                
                                                       }


         }
    
    
    
    
    
    
    }

Views/User/UserUpdateViewComponent.cs
using Microsoft.Graph;

using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;

using Microsoft.AspNetCore.Mvc;
using System.Text.RegularExpressions;

namespace GraphTutorial.Views.User{





    public class UserUpdateViewComponent : ViewComponent{



                    GraphServiceClient _graphClient{get;set;}

                public UserUpdateViewComponent ( GraphServiceClient graphClient)
                        
                    {
                        _graphClient = graphClient;
                        
                    }


                            public async Task<IViewComponentResult> InvokeAsync(){  
    


   
                                    return View();
                
                                                       }


         }
    
    
    
    
    
    
    }

Views/User/CreateUser.cshtml
@model Microsoft.Graph.User

    @{
        ViewData["Title"] = "CreateUser";
    }
    

     
    <h3>User Created:</h3>

        
        <p><label>Name:</label>
            @Model.DisplayName</p>

        <p><label>Email:</label>
            @Model.UserPrincipalName</p>


  

Views/User/DeleteUser.cshtml
@model Microsoft.Graph.User

    @{
        ViewData["Title"] = "DeleteUser";
    }
    

     
    <h3>User Deleted:</h3>

        
        <p><label>Name:</label>
            @Model.DisplayName</p>

        <p><label>Email:</label>
            @Model.UserPrincipalName</p>


  

Views/User/Home.cshtml
  @model Microsoft.Graph.IGraphServiceUsersCollectionPage
  
  @{
        ViewData["Title"] = "Home";
    }

<h3>Users</h3>
<div>
<div class="d-flex card-deck"> 
  
  
   @await Component.InvokeAsync("UserCreate")</div>
  @await Component.InvokeAsync("UserUpdate")</div>

<div>


  
<div> 
  
   @await Component.InvokeAsync("Index")</div>

<div>
</div>
@* <partial name="Index" model="@Model"/> *@


</div>

Views/User/Index.cshtml
@model Microsoft.Graph.IGraphServiceUsersCollectionPage

    @{
        ViewData["Title"] = "Users";
    }
    
        <h3>Users</h3>
                          <p class="d-flex">     
                              <a class="btn btn-primary nav-link m-1" asp-area="" asp-controller="User" asp-action="UserCreateForm">Create a new User</a>

                            <a class=" btn btn-info nav-link m-1" asp-area="" asp-controller="User" asp-action="UpdateUser">Update User</a>

                               <a class=" btn btn-danger nav-link m-1" asp-area="" asp-controller="User" asp-action="UserDeleteForm">Delete a User</a>
                               
                                <a class="nav-link btn m-1 p-2" asp-area="" asp-controller="User" asp-action="Home">Layout</a>
                            
                     </p>
    
    @foreach(var item in Model)
    {



        <span class="card card-body">
            <label> User:            </label>

           <p> @item.DisplayName</p>

            <label> Email:            </label>

            <p>  @item.Mail</p>

             <label>Alt. Email:</label>
            <p>  @item.UserPrincipalName</p>
            

            <hr/>
           </span> 


    }

Views/User/UpdateUser.cshtml
@model Microsoft.Graph.User

    @{
        ViewData["Title"] = "UpdateUser";
    }
    

 
        
        @Model.DisplayName
 

Views/User/UserCreateForm.cshtml
@model Microsoft.Graph.User

    @{
        ViewData["Title"] = "CreateUser";
    }
    

     <h3> Create A New User:</h3>


     <div class="col-12">
        <form asp-action="CreateUser">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
          
          
          
            <div class="form-group">
                <label asp-for="GivenName" class="control-label"></label>
                <input asp-for="GivenName" class="form-control"  />
                <span asp-validation-for="GivenName" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" id="text-box" class="form-control" style="padding-bottom: 5rem;
                                      padding-top: 1rem;"/>
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>


               <div class="form-group">
                <label class="control-label">Email:</label>
                <input asp-for="UserPrincipalName" id="text-box" class="form-control" style="padding-bottom: 5rem;
                                      padding-top: 1rem;"/>
                <span asp-validation-for="UserPrincipalName" class="text-danger"></span>
            </div>



            @Html.DisplayFor(model => model.Id)
            <div class="form-group">
                <input type="submit" value="Create User" class="btn btn-primary" />
            </div>

            
             </form>



           
           @section Scripts      
             {

    

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}



        }

Views/User/UserDeleteForm.cshtml
@model Microsoft.Graph.User

    @{
        ViewData["Title"] = "DeleteUser";
    }
    

     <h3> Delete a user:</h3>


     <div class="col-12">
        <form asp-action="DeleteUser">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
          
          
          
         

               <div class="form-group">
                <label class="control-label">Email:</label>
                <input asp-for="UserPrincipalName" id="text-box" class="form-control" style="padding-bottom: 5rem;
                                      padding-top: 1rem;"/>
                <span asp-validation-for="UserPrincipalName" class="text-danger"></span>
            </div>



            @Html.DisplayFor(model => model.Id)
            <div class="form-group">
                <input type="submit" value="Delete User" class="btn btn-danger" />
            </div>

            
             </form>



           
           @section Scripts      
             {

    

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}



        }