Controllers/OneDriveController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Identity.Web;
using Microsoft.Graph;
using System.IO;
using System.Collections.Generic;
using System.Threading.Tasks;


namespace GraphTutorial.Controllers{

 public class OneDriveController:Controller{

GraphServiceClient _graphClient{get;set;}

    public OneDriveController ( GraphServiceClient graphClient)
            
        {
            _graphClient = graphClient;
            
        }


             [HttpGet ]   
        [AuthorizeForScopes(Scopes = new[] { "Files.ReadWrite" })]
            public async Task<IActionResult> GetOneDrive(){


                            
            var drive = await _graphClient.Me.Drive.Root
                .Request()
                  .Select("items,id,list")
                .GetAsync();


                return View(drive);

            }



             [HttpGet ]   
        [AuthorizeForScopes(Scopes = new[] { "Files.ReadWrite" })]
            public async Task<IActionResult> GetFiles(){


             
                    var children = await _graphClient.Me.Drive.Root.Children
                .Request()
                .GetAsync();


                return View(children);

            }



             [HttpPost]   
        [AuthorizeForScopes(Scopes = new[] { "Files.ReadWrite" })]


        
            public async Task<IActionResult> UploadFile(){


                   string path = "wwwroot/img/Documents.ico";
            byte[] data = System.IO.File.ReadAllBytes(path);

        using (Stream stream = new MemoryStream(data))
            {   var item = await _graphClient.Me.Drive.Items[""]
                        .ItemWithPath("Documents.ico")
                        .Content
                        .Request()
                        .PutAsync<DriveItem>(stream);
            }

            //  await _graphClient.Me
            //         .Drive
            //         .Root   
            //         .ItemWithPath("img/Documents.ico")
            //         .Content
            //         .Request()
            //         .PutAsync<DriveItem>(stream);


                return View(data);

            }








 }
 
 }

Views/OneDrive/GetFiles.cshtml
@model Microsoft.Graph.DriveItemChildrenCollectionPage

    @{
        ViewData["Title"] = "GetFiles";
    }


 <h3>OneDrive Files/Folders</h3>

    <a class="nav-link btn m-5 col-3" asp-area="" asp-controller="OneDrive" asp-action="UploadFile">Upload</a>



<div class="row col ">




    @foreach (var item in Model){


      <span class="card card-body">  
          
            <p class="card-title"> <label >Namn: </label>
            
             @item.Name
            </p>

     

          
             
          @{if(@item.Folder != null){

             <p>  <label>Innehåll: </label>
       
   
           <a href="@item.WebUrl"><i><img height="50rem" src="/img/Folder.ico"></i>Se Mapp-Innehåll</a>
            </p>
            
            }}

         @{if(@item.Size != 0){

      @if(@item.Folder == null){

               <p>  <label>Fil-Adress: </label>
            
                  
                     <a href="@item.WebUrl"><i><img height="50rem" src="/img/Mime Blank.ico"></i>@item.WebUrl </a>
                        </p>
                        }
     
      } }


            <p>  <label>Storlek: </label>
       
           @{var size = @item.Size/1000000;
           
           
            } 
            @size Mb
            </p>
            
           
             <p>  <label>Skapad: </label>
       
           @item.CreatedDateTime
            </p>






         </span>    
    }
        
        </div>

Views/OneDrive/GetOneDrive.cshtml
@model Microsoft.Graph.DriveItem

    @{
        ViewData["Title"] = "GetOneDrive";
    }
    

     <h4>OneDrive</h4>


@*         
        

       *@

            

        @Model.Name
        
        @Model.FileSystemInfo

Views/OneDrive/UploadFile.cshtml
@model System.IO.FileStream

    @{
        ViewData["Title"] = "Uploadfile";
    }
    
    <h3>File Upload test</h3>

    File name:

        @Model.Name
    